blank_issues_enabled: false
contact_links:
  - name: Community Discussion
    url: https://github.com/flexume/flexume/discussions
    about: Please ask and answer questions here.
  - name: Security Issue
    url: https://github.com/flexume/flexume/security/advisories/new
    about: Please report security vulnerabilities here.